package com.Ecommerce.Project.enums;

public enum ErrorCode {
    INTERNAL_SERVER_ERROR,

    IDEMPOTENCY_RECORD_NOT_FOUND,

    IDEMPOTENCY_RETRY_FAILED,

    IDEMPOTENCY_STATE_TRANSITION_FAILED,

    IDEMPOTENCY_JSON_PROCESSING_FAILED
}
